---
- name: 'Configuration: Prepare empty volumes list'
  set_fact:
    nginx_container_volumes: []
  changed_when: false

- name: 'Configuration: Prepare config files volumes'
  set_fact:
    nginx_container_volumes: "{{ nginx_container_volumes + [ nginx_settings_path + '/conf.d:/etc/nginx/conf.d:ro'  ] }}"
  changed_when: nginx_config_files_status.changed

- name: 'Configuration: Prepare mounted folders volumes list'
  set_fact:
    nginx_container_volumes: "{{ nginx_container_volumes + [ nginx_settings_path + item.dst + ':' + item.dst + ':' + item.mode|default('ro')  ] }}"
  with_items: '{{ nginx_mounted_folders }}'
  changed_when: nginx_mounted_folders_status.changed
